name: Build app and push to S3

on:
  push:
    branches: ["dev", "master"]
  pull_request:
    branches: ["dev", "master"]

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
  DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: npx pnpm install
      - run: npx pnpm build
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: build
  push-to-s3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: build
      - name: Deploy static site to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TARGET_S3: ${{ env.BRANCH_NAME == 'master' && 's3://breathe.aumbadgah.com' || 's3://beta.breathe.aumbadgah.com' }}
        run: aws s3 sync ./dist/ ${{ env.TARGET_S3 }} --delete --region eu-central-1
